/**
 * Interpretation Assistant API
 * Phase 6.2 — Assisted Interpretation (Human-in-the-Loop)
 * 
 * Provides user-invoked interpretation assistance for understanding inference structure.
 * Assistant has ZERO authority - only restates, defines, or points to existing information.
 * 
 * STRICT RULES:
 * - No explanations of causes
 * - No recommendations or actions
 * - No predictions or comparisons
 * - Referential grounding mandatory (must reference specific stored fields)
 * - Language neutrality required
 */

import express, { Request, Response } from 'express'
import { getAnalysisRunById } from '../db/client.js'

const router = express.Router()

/**
 * Check if a user query should be refused
 */
function shouldRefuse(query: string): boolean {
  const lowerQuery = query.toLowerCase()
  
  // Refusal patterns: what to do, why, what will happen, comparisons
  const refusalPatterns = [
    /what (should|do|can) i (do|take|consider)/,
    /why (did|does|is|was)/,
    /what (will|would|might|could) (happen|occur|change)/,
    /which (is|are|was) (better|worse|best|worst)/,
    /compare/,
    /(should|recommend|suggest|advise|think)/,
    /(cause|caused|reason|because|due to)/,
    /(predict|forecast|future|next|coming)/,
  ]
  
  return refusalPatterns.some(pattern => pattern.test(lowerQuery))
}

/**
 * Generate refusal response
 */
function generateRefusal(): string {
  return "KurimaSense does not determine causes or recommend actions. I can explain what the recorded status, confidence, and categories mean if that helps."
}

/**
 * Define enum values
 */
function defineEnumValue(field: string, value: string): string {
  const definitions: Record<string, Record<string, string>> = {
    status: {
      healthy: "The stored status is 'healthy'. This indicates the system recorded healthy vegetation based on NDVI measurements.",
      watch: "The stored status is 'watch'. This indicates the system recorded moderate vegetation based on NDVI measurements.",
      stressed: "The stored status is 'stressed'. This indicates the system recorded stressed vegetation based on NDVI measurements.",
    },
    trend: {
      improving: "The stored trend is 'improving'. This indicates the system recorded an improving trend in crop health.",
      stable: "The stored trend is 'stable'. This indicates the system recorded a stable trend in crop health.",
      declining: "The stored trend is 'declining'. This indicates the system recorded a declining trend in crop health.",
    },
    confidence: {
      high: "The stored confidence is 'high'. This indicates the system recorded high confidence in the inference.",
      medium: "The stored confidence is 'medium'. This indicates the system recorded medium confidence in the inference.",
      low: "The stored confidence is 'low'. This indicates the system recorded low confidence in the inference.",
    },
  }
  
  return definitions[field]?.[value] || `The stored ${field} value is '${value}'.`
}

/**
 * Explain what a field represents
 */
function explainField(field: string): string {
  const explanations: Record<string, string> = {
    status: "The 'status' field records the crop health status determined by the system. Possible values are: healthy, watch, stressed.",
    trend: "The 'trend' field records the trend in crop health over the analysis window. Possible values are: improving, stable, declining.",
    confidence: "The 'confidence' field records the system's confidence level in the inference. Possible values are: high, medium, low.",
    categories: "The 'categories' field contains category records. Each category includes a category type and message recorded by the system.",
    explanation: "The 'explanation' field contains the text explanation recorded by the system for this inference.",
    generatedAt: "The 'generatedAt' field records when the inference was generated by the system.",
  }
  
  return explanations[field] || `The '${field}' field is part of the stored inference data.`
}

/**
 * Generate interpretation response
 * 
 * Phase 6.2: Only restates, defines, or explains existing stored fields.
 * Must reference specific stored fields explicitly.
 */
function generateInterpretation(query: string, inference: any): string {
  const lowerQuery = query.toLowerCase()
  
  // Check for enum value queries
  if (inference.status && (lowerQuery.includes('status') || lowerQuery.includes('health'))) {
    return defineEnumValue('status', inference.status)
  }
  
  if (inference.trend && lowerQuery.includes('trend')) {
    return defineEnumValue('trend', inference.trend)
  }
  
  if (inference.confidence && lowerQuery.includes('confidence')) {
    return defineEnumValue('confidence', inference.confidence)
  }
  
  // Check for field explanation queries
  if (lowerQuery.includes('category') || lowerQuery.includes('categories')) {
    if (inference.categories && inference.categories.length > 0) {
      const categoryInfo = inference.categories.map((cat: any, idx: number) => 
        `Category ${idx + 1}: The system recorded category '${cat.category}' with message "${cat.message}".`
      ).join(' ')
      return explainField('categories') + ' ' + categoryInfo
    }
    return explainField('categories')
  }
  
  if (lowerQuery.includes('explanation')) {
    if (inference.explanation) {
      return explainField('explanation') + ` The stored explanation is: "${inference.explanation}"`
    }
    return explainField('explanation')
  }
  
  if (lowerQuery.includes('field')) {
    return "The stored inference includes these fields: status, trend, confidence, categories, explanation, generatedAt, fieldId. I can explain what any of these represent."
  }
  
  // Default: explain available fields
  return "I can explain what the stored inference fields represent: status, trend, confidence, categories, and explanation. What would you like to know about?"
}

/**
 * POST /api/interpretation/assist
 * Get interpretation assistance for an analysis run
 * 
 * Body:
 * - analysisRunId: string (required)
 * - query: string (required)
 * 
 * Contract: Returns interpretation that only restates, defines, or explains stored fields.
 * No causes, recommendations, predictions, or comparisons.
 */
router.post('/assist', (req: Request, res: Response) => {
  try {
    const { analysisRunId, query } = req.body

    if (!analysisRunId || typeof analysisRunId !== 'string') {
      return res.status(400).json({
        success: false,
        error: 'analysisRunId is required'
      })
    }

    if (!query || typeof query !== 'string' || query.trim().length === 0) {
      return res.status(400).json({
        success: false,
        error: 'query is required'
      })
    }

    // Get the analysis run
    const run = getAnalysisRunById(analysisRunId)
    
    if (!run) {
      return res.status(404).json({
        success: false,
        error: 'Analysis run not found'
      })
    }

    // Check if query should be refused
    if (shouldRefuse(query)) {
      return res.json({
        success: true,
        data: {
          response: generateRefusal(),
          refused: true,
        }
      })
    }

    // Generate interpretation (only references stored inference)
    const inference = run.inference
    const response = generateInterpretation(query, inference)

    res.json({
      success: true,
      data: {
        response,
        refused: false,
      }
    })
  } catch (error) {
    console.error('Error generating interpretation:', error)
    res.status(500).json({
      success: false,
      error: 'Failed to generate interpretation'
    })
  }
})

export default router

